const text1 = "Num universo urbano, onde o pulsar constante da cidade se entrelaça com o cotidiano das pessoas, cada esquina conta uma história. Edifícios altos tocam os céus, testemunhas silenciosas do frenesi diário. Nas ruas movimentadas, transeuntes apressados tecem os fios da vida, cada passo uma dança efêmera na coreografia urbana. À sombra de cafés aconchegantes, o aroma do café se mistura ao zumbido de conversas e risadas, criando um cenário acolhedor para mentes inquietas. Janelas revelam vistas panorâmicas da metrópole, suas luzes noturnas cintilando como estrelas urbanas. Em praças, artistas de rua desafiam a gravidade, enquanto músicos entoam melodias que ecoam entre arranha-céus. O pulsar da cidade, por vezes ensurdecedor, é interrompido pelo sussurro dos parques, o verde rompendo o concreto em um lembrete sereno da natureza. No entanto, sob a fachada vibrante, existem histórias individuais, anseios e sonhos que ecoam nos becos e vielas. Cada rosto na multidão carrega uma narrativa única, uma peça no intricado quebra-cabeça da vida urbana. Assim, a cidade se desdobra como um livro aberto, suas páginas escritas pelas vidas que a habitam. Uma sinfonia caótica, onde cada nota contribui para a vibrante melodia da existência urbana."

const text2 = "No cenário tranquilo de uma pequena cidade, onde o tempo parecia desacelerar, a vida seguia seu curso sereno. As ruas de paralelepípedos testemunhavam o cotidiano dos moradores, enquanto o sol lançava seus raios dourados sobre fachadas coloridas. Na praça central, idosos trocavam histórias à sombra de árvores centenárias, compartilhando experiências de uma vida bem vivida. À medida que o dia avançava, aromas tentadores emanavam das cozinhas locais, despertando o apetite de quem passeava pelas ruelas charmosas. Na padaria, o padeiro meticuloso preparava pães frescos, inundando o ambiente com cheiros reconfortantes. Crianças corriam animadas pelos parques, suas risadas ecoando entre as árvores, enquanto os pássaros, em um ballet aéreo, proporcionavam uma trilha sonora natural. À noite, a cidade ganhava uma atmosfera mágica, com as luzes suaves iluminando as fachadas e criando um ambiente acolhedor. Nas praças, músicos locais entoavam melodias que acalmavam os corações dos transeuntes. Sob um céu estrelado, a comunidade compartilhava o presente, celebrando a simplicidade da vida em um lugar onde as relações humanas se entrelaçavam como os fios de uma tapeçaria, formando a rica trama de uma história coletiva"

const text3 = "Em um rincão tranquilo, onde o tempo flui suavemente como um riacho serpenteante, a vida se desenrola em harmonia com a natureza. Campos ondulantes estendem-se até onde a vista alcança, pintados em tonalidades verdejantes que dançam ao sabor da brisa suave. Árvores antigas, guardiãs do passado, espalham sombras benevolentes sobre caminhos de terra que contam histórias de tempos imemoriais. Pequenas casas de campo, com seus telhados de palha, parecem abraçar a simplicidade, enquanto flores selvagens emolduram portas e janelas. O trinar melódico dos pássaros preenche o ar, criando uma sinfonia natural que ecoa entre colinas e vales. No centro dessa idílica paisagem, um riacho murmura segredos antigos, suas águas límpidas refletindo o céu azul. Pescadores pacientes alinham suas margens, conectando-se com a paciência do tempo. Borboletas dançam entre flores, suas asas coloridas pintando a paisagem com pinceladas efêmeras. À noite, o céu se transforma em um espetáculo de estrelas, como se cada ponto de luz fosse uma história celestial a ser contada. Um silêncio sereno envolve a aldeia, onde as luzes suaves das casas transmitem uma sensação de aconchego. Assim, nesse refúgio bucólico, a vida se desenrola em um ritmo compassado, lembrando-nos da beleza simples e eterna que existe na conexão com a terra e seus ciclos."

let texts = [text1, text2, text3]

const choice = Math.floor(Math.random() * texts.length);

export default texts[choice];